Have mg automatically run make when it sees a makefile

diff --git a/bin/mg b/bin/mg
--- a/bin/mg
+++ b/bin/mg
@@ -86,6 +86,11 @@ do_sync () {
     echo "==> $name: $r (pull)"
     git pull > /dev/null 2>&1 || die "failed to git pull"
 
+    if [ -r Makefile -o -r GNUmakefile ]; then
+      echo "==> $name: $r (make)"
+      make > /dev/null 2>&1 || die "make failed"
+    fi
+
     if git_repo_needs_push; then
       echo "==> $name: $r (push)"
       git push > /dev/null 2>&1 || die "failed to git push"
