Update EOD, better org-mode stuff

diff --git a/zsh/bin/eod b/zsh/bin/eod
--- a/zsh/bin/eod
+++ b/zsh/bin/eod
@@ -21,61 +21,69 @@ git_repositories="
 # Test to see if a repository has any uncommitted changes
 eod_git_repo_has_changes ()
 {
-    if ! git-status|grep -q -F '(working directory clean)'; then
-        return 0
-    else
-        return 1
-    fi
+  if ! git-status|grep -q -F '(working directory clean)'; then
+    return 0
+  else
+    return 1
+  fi
 }
 
 ################################################################################
 # Push all Git repositories back to pmade.com
 eod_git_push_all_repositories ()
 {
-    for repo in $git_repositories; do
-        eval "repo=$repo"
-        
-        if test -d $repo; then
+  for repo in $git_repositories; do
+    eval "repo=$repo"
+    
+    if test -d $repo; then
             # echo "==> sync $repo"
-            cd $repo || die "failed cd"
-            
-            if eod_git_repo_has_changes; then
-                die "uncommitted changes in $repo"
-            fi
+      cd $repo || die "failed cd"
+      
+      if eod_git_repo_has_changes; then
+        die "uncommitted changes in $repo"
+      fi
 
-            git-pull > /dev/null 2>&1 || die "failed pull"
-            git-push > /dev/null 2>&1 || die "failed push"
-        fi
-    done
+      git-pull > /dev/null 2>&1 || die "failed pull"
+      git-push > /dev/null 2>&1 || die "failed push"
+    fi
+  done
 }
 
 ################################################################################
 # Commit certain repositories without intervention
 eod_git_commit_repositories ()
 {
-    for repo in $git_commit_repos; do
-        eval "cd $repo" || die "failed cd"
+  for repo in $git_commit_repos; do
+    eval "cd $repo" || die "failed cd"
 
-        if eod_git_repo_has_changes; then
-            # echo "==> ci $repo"
-            git-add . > /dev/null || die "failed git-add"
-            git-commit -m "end of day commit" > /dev/null || die "failed commit"
-        fi
-    done
+    if eod_git_repo_has_changes; then
+      # echo "==> ci $repo"
+      git-add . > /dev/null || die "failed git-add"
+      git-commit -m "end of day commit" > /dev/null || die "failed commit"
+    fi
+  done
 }
 
 ################################################################################
 # Sync ~/.comm-sync
 eod_comm_sync ()
 {
-    comm-sync || exit 1
+  (cd ~/.comm-sync && sh bin/install.sh) || exit 1
+  comm-sync || exit 1
+}
+
+################################################################################
+# Install all rc files from ~/Develop/pmade/rc
+eod_install_rc ()
+{
+  (cd $HOME/Develop/pmade/rc && make) || die 'rc install failed'
 }
 
 ################################################################################
 die ()
 {
-    echo "ERROR: $1" > /dev/stderr
-    exit 1
+  echo "ERROR: $1" > /dev/stderr
+  exit 1
 }
 
 ################################################################################
@@ -86,3 +94,6 @@ eod_git_push_all_repositories || die "eod_git_push_all_repositories"
 
 echo "==> comm-sync"
 eod_comm_sync || die "eod_comm_sync"
+
+echo "==> install rc"
+eod_install_rc || die "eod_install_rc"
